import { chromium } from 'playwright';
const BASE = 'http://localhost:4173/';
const OUT = process.env.SHOT_DIR || 'scripts/shots';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await b.newPage({ viewport: { width: 390, height: 844 } });
await page.goto(BASE);
await page.evaluate(() => { localStorage.clear(); localStorage.setItem('hh_dev', '1'); });
await page.reload();
await page.waitForTimeout(2800);
await page.screenshot({ path: `${OUT}/01-lucky.png` });

const jump = async (n, name, wait = 900) => {
  await page.getByRole('button', { name: 'DEV', exact: true }).click();
  await page.getByRole('button', { name: new RegExp(`^${n} `) }).click();
  await page.getByRole('button', { name: 'close', exact: true }).click();
  await page.waitForTimeout(wait);
  await page.screenshot({ path: `${OUT}/${name}.png`, fullPage: true });
};
await jump(1, '02-scratch');
await jump(2, '03-inflate');
await jump(3, '04-chug');
await jump(4, '05-wheel');
await jump(5, '06-sign');
await jump(6, '07-seal');
await page.getByRole('button', { name: 'DEV', exact: true }).click();
await page.getByRole('button', { name: 'finale', exact: true }).click();
await page.getByRole('button', { name: 'close', exact: true }).click();
await page.waitForTimeout(2000);
await page.screenshot({ path: `${OUT}/08-finale.png` });
await page.getByRole('button', { name: 'VIEW YOUR RECORD' }).click();
await page.waitForTimeout(600);
await page.screenshot({ path: `${OUT}/09-record.png`, fullPage: true });
await b.close();
console.log('shots done');
